apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: '{{ .Values.services.uaa.name }}'
  labels:
    app.kubernetes.io/name: '{{ .Values.services.uaa.name }}'
spec:
  externalName: '{{ .Values.services.uaa.name }}'
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: '{{ .Values.services.uaa.xsappname }}'
    tenant-mode: dedicated
<% if(authorization){ -%>
    scopes:
      - name: $XSAPPNAME.Viewer
        description: Viewer
    role-templates:
      - name: Viewer
        description: Viewer
        scope-references:
          - $XSAPPNAME.Viewer
    role-collections:
      - name: '{{ .Values.services.uaa.xsappname }}_Viewer'
        description: '{{ .Values.services.uaa.xsappname }} Viewer'
        role-template-references:
          - $XSAPPNAME.Viewer
<% }else{ -%>
    scopes:
      - name: uaa.user
        description: Token Exchange
    role-templates:
      - name: TOKEN_EXCHANGE
        description: User
        scope-references:
          - uaa.user
<% } -%>
    oauth2-configuration:
      redirect-uris:
        - 'https://{{ .Values.services.app.name }}.{{ .Values.clusterDomain }}/login/callback'